/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Model.Pedido;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class Farmacia extends javax.swing.JFrame {
    
    /**
     * Creates new form Farmacia
     * 
     */
    
    public Farmacia() {
        
        initComponents();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btbgroup_distribuidoras = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblnombre = new javax.swing.JLabel();
        lbltipo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblcantidad = new javax.swing.JLabel();
        lblsucursal = new javax.swing.JLabel();
        lbldistribuidor = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtNombreMedicamentos = new javax.swing.JTextField();
        Combobox_tipo = new javax.swing.JComboBox<>();
        txt_cantidad = new javax.swing.JTextField();
        rdbtb_COFARMA = new javax.swing.JRadioButton();
        rdbtb_EMPSEPHAR = new javax.swing.JRadioButton();
        rdbtb_CEMEFAR = new javax.swing.JRadioButton();
        check_principal = new javax.swing.JCheckBox();
        check_secundaria = new javax.swing.JCheckBox();
        btb_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setText("TIENDA DE MEDICAMENTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(155, 155, 155))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        lblnombre.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblnombre.setText("Nombre:");

        lbltipo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbltipo.setText("Tipo:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel4.setText("M E D I C A M E N T O");

        lblcantidad.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblcantidad.setText("Cantidad:");

        lblsucursal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblsucursal.setText("Sucursal:");

        lbldistribuidor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbldistribuidor.setText("Distribuidor farmaceutico:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblnombre))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblcantidad))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblsucursal))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbltipo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbldistribuidor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(17, 17, 17)
                .addComponent(lblnombre)
                .addGap(28, 28, 28)
                .addComponent(lbltipo)
                .addGap(18, 18, 18)
                .addComponent(lblcantidad)
                .addGap(32, 32, 32)
                .addComponent(lbldistribuidor)
                .addGap(30, 30, 30)
                .addComponent(lblsucursal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Combobox_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo ", "Antibiótico" }));

        btbgroup_distribuidoras.add(rdbtb_COFARMA);
        rdbtb_COFARMA.setText("COFARMA");

        btbgroup_distribuidoras.add(rdbtb_EMPSEPHAR);
        rdbtb_EMPSEPHAR.setText("EMPSEPHAR");

        btbgroup_distribuidoras.add(rdbtb_CEMEFAR);
        rdbtb_CEMEFAR.setText("CEMEFAR");

        check_principal.setText("PRINCIPAL");

        check_secundaria.setText("SECUNDARIA");

        btb_ok.setText("OK");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(check_principal)
                                .addGap(18, 18, 18)
                                .addComponent(check_secundaria))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rdbtb_COFARMA)
                                .addGap(18, 18, 18)
                                .addComponent(rdbtb_EMPSEPHAR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdbtb_CEMEFAR))
                            .addComponent(txtNombreMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Combobox_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btb_ok)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtNombreMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Combobox_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtb_COFARMA)
                    .addComponent(rdbtb_EMPSEPHAR)
                    .addComponent(rdbtb_CEMEFAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_principal)
                    .addComponent(check_secundaria))
                .addGap(26, 26, 26)
                .addComponent(btb_ok)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public JComboBox<String> getCombobox_tipo() {
        return Combobox_tipo;
    }

    public void setCombobox_tipo(JComboBox<String> Combobox_tipo) {
        this.Combobox_tipo = Combobox_tipo;
    }

    public JButton getBtb_ok() {
        return btb_ok;
    }

    public void setBtb_ok(JButton btb_ok) {
        this.btb_ok = btb_ok;
    }

    public ButtonGroup getBtbgroup_distribuidoras() {
        return btbgroup_distribuidoras;
    }

    public void setBtbgroup_distribuidoras(ButtonGroup btbgroup_distribuidoras) {
        this.btbgroup_distribuidoras = btbgroup_distribuidoras;
    }

    public JCheckBox getCheck_principal() {
        return check_principal;
    }

    public void setCheck_principal(JCheckBox check_principal) {
        this.check_principal = check_principal;
    }

    public JCheckBox getCheck_secundaria() {
        return check_secundaria;
    }

    public void setCheck_secundaria(JCheckBox check_secundaria) {
        this.check_secundaria = check_secundaria;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JLabel getLblcantidad() {
        return lblcantidad;
    }

    public void setLblcantidad(JLabel lblcantidad) {
        this.lblcantidad = lblcantidad;
    }

    public JLabel getLbldistribuidor() {
        return lbldistribuidor;
    }

    public void setLbldistribuidor(JLabel lbldistribuidor) {
        this.lbldistribuidor = lbldistribuidor;
    }

    public JLabel getLblnombre() {
        return lblnombre;
    }

    public void setLblnombre(JLabel lblnombre) {
        this.lblnombre = lblnombre;
    }

    public JLabel getLblsucursal() {
        return lblsucursal;
    }

    public void setLblsucursal(JLabel lblsucursal) {
        this.lblsucursal = lblsucursal;
    }

    public JLabel getLbltipo() {
        return lbltipo;
    }

    public void setLbltipo(JLabel lbltipo) {
        this.lbltipo = lbltipo;
    }

    public JRadioButton getRdbtb_CEMEFAR() {
        return rdbtb_CEMEFAR;
    }

    public void setRdbtb_CEMEFAR(JRadioButton rdbtb_CEMEFAR) {
        this.rdbtb_CEMEFAR = rdbtb_CEMEFAR;
    }

    public JRadioButton getRdbtb_COFARMA() {
        return rdbtb_COFARMA;
    }

    public void setRdbtb_COFARMA(JRadioButton rdbtb_COFARMA) {
        this.rdbtb_COFARMA = rdbtb_COFARMA;
    }

    public JRadioButton getRdbtb_EMPSEPHAR() {
        return rdbtb_EMPSEPHAR;
    }

    public void setRdbtb_EMPSEPHAR(JRadioButton rdbtb_EMPSEPHAR) {
        this.rdbtb_EMPSEPHAR = rdbtb_EMPSEPHAR;
    }

    public JTextField getTxtNombreMedicamentos() {
        return txtNombreMedicamentos;
    }

    public void setTxtNombreMedicamentos(JTextField txtNombreMedicamentos) {
        this.txtNombreMedicamentos = txtNombreMedicamentos;
    }

    public JTextField getTxt_cantidad() {
        return txt_cantidad;
    }

    public void setTxt_cantidad(JTextField txt_cantidad) {
        this.txt_cantidad = txt_cantidad;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Farmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Farmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Farmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Farmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Farmacia().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combobox_tipo;
    private javax.swing.JButton btb_ok;
    private javax.swing.ButtonGroup btbgroup_distribuidoras;
    private javax.swing.JCheckBox check_principal;
    private javax.swing.JCheckBox check_secundaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblcantidad;
    private javax.swing.JLabel lbldistribuidor;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblsucursal;
    private javax.swing.JLabel lbltipo;
    private javax.swing.JRadioButton rdbtb_CEMEFAR;
    private javax.swing.JRadioButton rdbtb_COFARMA;
    private javax.swing.JRadioButton rdbtb_EMPSEPHAR;
    private javax.swing.JTextField txtNombreMedicamentos;
    private javax.swing.JTextField txt_cantidad;
    // End of variables declaration//GEN-END:variables

    
}
