/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Pedido;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class resumen_pedido extends javax.swing.JFrame {
    private Pedido pedido;

    /**
     * Creates new form resumen_pedido
     */
    public resumen_pedido(Pedido p) {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(this);
        this.setTitle("       Pedido al Distribuidor     "  );
        this.pedido = p;
        mostrar();
    }
    
    public void mostrar(){
        lbl_unidades.setText(pedido.getCantidad());
        lbl_tipo.setText(pedido.getTipo_medicamento());
        lbl_nombre.setText(pedido.getNombre());
        lbl_nombrepedido.setText(pedido.getDistribuidor());
        lbl_direccion.setText(pedido.getDireccion());
    }

    public JButton getBtb_cancelar() {
        return btb_cancelar;
    }

    public void setBtb_cancelar(JButton btb_cancelar) {
        this.btb_cancelar = btb_cancelar;
    }

    public JButton getBtb_enviar() {
        return btb_enviar;
    }

    public void setBtb_enviar(JButton btb_enviar) {
        this.btb_enviar = btb_enviar;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getLbl_direccion() {
        return lbl_direccion;
    }

    public void setLbl_direccion(JLabel lbl_direccion) {
        this.lbl_direccion = lbl_direccion;
    }

    public JLabel getLbl_nombre() {
        return lbl_nombre;
    }

    public void setLbl_nombre(JLabel lbl_nombre) {
        this.lbl_nombre = lbl_nombre;
    }

    public JLabel getLbl_nombrepedido() {
        return lbl_nombrepedido;
    }

    public void setLbl_nombrepedido(JLabel lbl_nombrepedido) {
        this.lbl_nombrepedido = lbl_nombrepedido;
    }

    public JLabel getLbl_tipo() {
        return lbl_tipo;
    }

    public void setLbl_tipo(JLabel lbl_tipo) {
        this.lbl_tipo = lbl_tipo;
    }

    public JLabel getLbl_unidades() {
        return lbl_unidades;
    }

    public void setLbl_unidades(JLabel lbl_unidades) {
        this.lbl_unidades = lbl_unidades;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_nombrepedido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_unidades = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_tipo = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_direccion = new javax.swing.JLabel();
        btb_enviar = new javax.swing.JButton();
        btb_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        lbl_nombrepedido.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lbl_nombrepedido.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_nombrepedido, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_nombrepedido)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel1.setText("Pedido:");

        lbl_unidades.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lbl_unidades.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel2.setText("unidades del");

        lbl_tipo.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lbl_tipo.setText("jLabel3");

        lbl_nombre.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lbl_nombre.setText("jLabel3");

        lbl_direccion.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lbl_direccion.setText("jLabel3");

        btb_enviar.setText("E N V I A R");
        btb_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btb_enviarActionPerformed(evt);
            }
        });

        btb_cancelar.setText("C A N C E L A R");
        btb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btb_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_unidades)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(btb_enviar)
                                .addGap(84, 84, 84)
                                .addComponent(btb_cancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(lbl_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 75, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_unidades)
                    .addComponent(jLabel2)
                    .addComponent(lbl_tipo)
                    .addComponent(lbl_nombre))
                .addGap(18, 18, 18)
                .addComponent(lbl_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btb_enviar)
                    .addComponent(btb_cancelar))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btb_cancelarActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "¿Seguro que desea Cancelar", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {
               this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "ok");
                }
            
    }//GEN-LAST:event_btb_cancelarActionPerformed

    private void btb_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btb_enviarActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Pedido Enviado");
    }//GEN-LAST:event_btb_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resumen_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resumen_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resumen_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resumen_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btb_cancelar;
    private javax.swing.JButton btb_enviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_nombrepedido;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JLabel lbl_unidades;
    // End of variables declaration//GEN-END:variables
}
